### ISSUE TITLE
managing collaboration with Redwood

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#1]
How do you all want to manage collaboration with Redwood?

Simple example (I'll open an issue for this):
controller_manager depends on pr2_controller_interface. I want to change the manifest.xml but would rather not be pushing to master.

Do you want to try having me fork and send pull requests? I haven't done this before so I don't know exactly what will happen and I'm unsure how this would work once Redwood has more than one person committing code.

Alternately, I could create a Redwood branch and let you all merge it back into master if useful?

**Comment by sachinchitta** [comment]
I would do a fork (for Redwood) and then once you are sure of the changes, do a pull request. Someone other than you will approve the pull request and merge it. This is a solution we are transitioning to for most code bases.
