### ISSUE TITLE
another question about realtime safety of ControlManager.update

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#10]
Hi Wim,

I just started to look at what it would take to switch control modes.

I noticed that STL vectors are getting cleared within the please_switch_ code block.

I'm guessing that this would not be realtime safe.

In this case we could probably clear the vectors in the switchController function?

**Comment by wmeeusse** [comment]
Fixed in the default branch. Moved the clear() calls to non-realtime
