### ISSUE TITLE
Determining Interface Used

### ISSUE THREAD

**Issue by kphawkins** [ros-controls/ros_control#102]
I'm writing an implementation of RobotHW and I need to expose multiple joint interfaces, each of which could potentially claim the same joints.  In the read/write update loop, how do I determine which interface is currently commanding the joints?  I can think of a couple ways to do this indirectly, but I would like to know if there is a direct way or at least an "accepted way".

My current implementation uses a _command mode_ parameter which the controller is obligated to set based on the interface being used.  This seems like a really messy way of doing things.

I'm probably going to switch to a method which sets all command variables to NaN, then checks them all at read time to see which one updated.

**Comment by adolfo-rt** [comment]
There's a similar discussion going on at #99, let's continue over there.
