### ISSUE TITLE
Joint limits interface: Test rostest+gtest integration.

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#106]
According to [this](https://github.com/ros/ros_comm/issues/258) ros_comm issue, the rostest+gtest combination does not seem to be well supported in Catkin. Further, I apparently added a test the wrong way in the joint_limits_interface package, as per the answer to this [question](http://answers.ros.org/question/54075/how-does-rostest-work-with-catkin/?comment=69673#comment-69673).

At this moment, I'll allow the ros_comm issue to evolve a bit, as I don't see clearly how to proceed.

**Comment by davetcoleman** [comment]
+1 for working on tests, i hope this gets resolved!

**Comment by adolfo-rt** [comment]
Me too. The test code is there. It just needs to get exercised under Catkin.

**Comment by adolfo-rt** [comment]
rostest+gtest integration has been working fine for quite some time.
