### ISSUE TITLE
Rename Branches

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#110]
I'd like to cleanup the branches in this repo, feedback welcomed, similar to what I did in [ros_controllers](https://github.com/ros-controls/ros_controllers/issues/34)

fuerte-dev  --> **fuerte-devel**
fuerte - REMOVE - this is the same as fuerte-dev
groovy-dev --> **groovy-devel**
groovy - REMOVE - this is the same as groovy-dev
**hydro-devel** - keep
master - REMOVE - this is behind hydro-devel by a lot of commits and not really needed
pr2-mechanism-release - keep because i'm not sure what its for

the "devel" name is a standard the ROS community seems to have settled on

**Comment by adolfo-rt** [comment]
+1

**Comment by davetcoleman** [comment]
Completed.
