### ISSUE TITLE
Invalid actuator and joint TiXmlElement pointers

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#112]
The [JointInfo](https://github.com/ros-controls/ros_control/blob/hydro-devel/transmission_interface/include/transmission_interface/transmission_info.h#L61) and [ActuatorInfo](https://github.com/ros-controls/ros_control/blob/hydro-devel/transmission_interface/include/transmission_interface/transmission_info.h#L70) structs contain `TiXmlElement*` instances to transmission-specific configuration. The current parser implementation has the issue that these pointers are only valid during the lifetime of the associated [TiXmlDocument](https://github.com/ros-controls/ros_control/blob/hydro-devel/transmission_interface/src/transmission_parser.cpp#L44) instance, which goes out of scope when `parse(...)` returns. This means that we basically can't use this pointers.

Two solutions come to mind:
- Make the parser stateful and store a `TiXmlDocument` instance. In this case pointers will only be valid as long as the parser is alive.
- Store strings instead of pointers with the contents of the `TiXmlElement`. The parser remains stateless, and the transmission plugins would only have to convert this string to a TinyXml data structure.

I prefer the second option, and will be implementing it.

@davetcoleman

**Comment by davetcoleman** [comment]
Ah, I never actually used those pointers so missed that bug! Feel free to change whatever is needed in those structs - my attention has turned back to grad school projects :)

**Comment by adolfo-rt** [comment]
Proposed solution has been merged. Closing.
