### ISSUE TITLE
ros_control fixes for integration with meta-ros layer

### ISSUE THREAD

**Issue by vmayoral** [ros-controls/ros_control#113]
Hi,

I'm providing a patch that applies some fixes to improve the ros_control code compatibility with [meta-ros](https://github.com/bmwcarit/meta-ros) (ROS Layer for OpenEmbedded Linux).

The patch is available [here](https://gist.github.com/vmayoral/6520685). Could this fixes be included in your next release?

**Comment by davetcoleman** [comment]
So it looks like Catkin testing needs to be disabled for meta-ros? That is all this does, right? Seems fine to me.

Also, simply submitting a pull request instead of a Gist-diff is usually the easiest way to propose code changes on Github.

**Comment by vmayoral** [comment]
Yes, that's what it does.

Perfect then, i'll submit a pull request.
