### ISSUE TITLE
EffortJointSoftLimitsHandle constructor requires soft_limits

### ISSUE THREAD

**Issue by jim-rothrock** [ros-controls/ros_control#115]
The EffortJointSoftLimitsHandle constructor requires a soft_limits argument, even though the URDF specification states that the <safety_controller> element is optional. My robot's URDF file does not contain safety controllers, so I'm passing a dummy soft_limits to EffortJointSoftLimitsHandle() in my version of default_robot_hw_sim.cpp. This isn't working well, since control is sensitive to the default values I store in the dummy soft_limits. I've thought of two solutions:

1) Create an EffortJointSaturationHandle class that works like EffortJointSoftLimitsHandle, except that only "limits" is used (no soft_limits). writeSim() in default_robot_hw_sim.cpp would have to make calls to the enforceLimits() member functions for both the soft limits and saturation interfaces.

2) Add an additional constructor to EffortJointSoftLimitsHandle, which does not have a soft_limits parameter. A has_soft_limits member variable would control whether computations were made with "limits" or "soft_limits".

Let me know which solution you prefer, or if whether you have an alternative solution.

**Comment by adolfo-rt** [comment]
If all you want is to implement a simple position/velocity/effort saturation, 1) is the way to go. The handle constructor would then only require a joint limits specification, but not soft limits.

If you still want to make some sense of the soft limit values, an explanation can be found [here]{http://wiki.ros.org/pr2_controller_manager/safety_limits}.

**Comment by jim-rothrock** [comment]
I implemented option 1.
