### ISSUE TITLE
rqt Controller Manager Plugin

### ISSUE THREAD

**Issue by kphawkins** [ros-controls/ros_control#125]
Does this exist anywhere?  Would people be interested in something like this?  I might throw one together if I get the time and it doesn't exist.  I'd just like to visualize the currently active controllers, stop/start them, and possibly load/unload.

**Comment by davetcoleman** [comment]
+1 This would be a very much appreciated feature! No, it does not exist yet.

**Comment by adolfo-rt** [comment]
Great idea, I'd love to see this happen!. You have my support for discussions and testing.

**Comment by jbohren** [comment]
Has anything been put together to this end?

**Comment by 130s** [comment]
I added this to rqt plugin's [ongoing work list](http://wiki.ros.org/rqt/Plugins#Plugins_currently_in_development) in trial to raise attention.

**Comment by kphawkins** [comment]
I might have some time to work on this over the next week or so.

**Comment by adolfo-rt** [comment]
> I added this to rqt plugin's ongoing work list in trial to raise attention.

I don't know if it's actually work in progress. @kphawkins, did you end up picking this one up?.

**Comment by adolfo-rt** [comment]
Wow, posts crossed!. Great to hear!

**Comment by kphawkins** [comment]
https://github.com/ros-controls/ros_control/pull/132 <- Initial release.
