### ISSUE TITLE
Parse transmissions from URDF

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#133]
I plan to start pushing incrementally the work I did during the summer on transmission parsing. This issue will serve as a reference for individual pull requests.

I'll start with some prerequisites that are not directly related to the transmission parsing, but are still required, and once we agree on them, I'll submit the actual code that automates populating transmission and joint interfaces.

**Comment by adolfo-rt** [comment]
If nobody voices any concerns, I'll merge the first three PRs on Tuesday Dec 10. This will unblock the next set of patches.

**Comment by davetcoleman** [comment]
I'm out of town but look forward to your improvements on transmission parsing as we discussed last summer. Keep up the good work!
