### ISSUE TITLE
Controller not being started in Controller_manager

### ISSUE THREAD

**Issue by PeterQFR** [ros-controls/ros_control#139]
I had a problem whereby my controller's update() function was not being called. Additionally the Starting routine was not called either. It was being initialised.

I looked through the code and realised that in the controller_manager.cpp, the function:

ControllerManager::loadController(const std::string& name) 

initialised the controller but at no stage did it start the controller. In ControllerBase, the update routine, requires the controller to be running before it will let the controller update.

The fix:

I adjusted the source in ControllerManager::loadController() on line 247, to start the controller with:

c->startRequest(ros::Time::now());

and recompiled. The controller_manager now works correctly and I can see my controller update() code running.

**Comment by adolfo-rt** [comment]
Please see my reply [here](http://answers.ros.org/question/119316/controller-manager-not-calling-controllerupdate-routine/?answer=119496#post-id-119496).
