### ISSUE TITLE
Releasing: ros_control, ros_controllers, realtime_tools, and controls_toolbox

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#140]
The Gazebo team (@hsu) has indicated gazebo_ros_pkgs is waiting for the ros_control packages to be released due to some changes preventing the Gazebo interface from compiling. Anyone object to me releasing these packages to bloom within the next couple days? @adolfo-rt

**Comment by adolfo-rt** [comment]
OK for me!

**Comment by davetcoleman** [comment]
I've released ros_control and ros_controllers
https://github.com/ros/rosdistro/pull/3013
https://github.com/ros/rosdistro/pull/3014

I don't have access to 
https://github.com/ros-gbp/control_toolbox-release
https://github.com/ros-gbp/realtime_tools-release
so I can't release that patch (though the patches aren't super necessary). @ahendrix @wjwwood  ?

**Comment by wjwwood** [comment]
I can give you access if you want.

**Comment by davetcoleman** [comment]
I'm willing to take that on.

**Comment by wjwwood** [comment]
Ok, your team (`ros-gbp/ros_control`) should have access now.

**Comment by davetcoleman** [comment]
Done:
https://github.com/ros/rosdistro/pull/3015
https://github.com/ros/rosdistro/pull/3016
