### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#152]
For anyone getting these emails (@adolfo) is there anyone working on getting the ros_control packages released into indigo? I personally haven't setup indigo yet since the new Ubuntu isn't released yet, but I know that method exists (chroot) to install ROS Indigo. I'm more inclined to wait until Ubuntu is released before bothering with Indigo (I'm a busy grad student), but this Gazebo issue https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179 has me worried about ros_control's continued support.

On another note, I'd like to suggest all `manifest.xml`, `stack.xml`, and dual-CMake files be cleaned up/removed from the Indigo branch so as to remove all rosbuild support, since Fuerte users should be hopefully migrating by this release. Thoughts?

**Comment by chadrockey** [comment]
@davetcoleman I don't work on ros_control, but I have released into indigo by installing the 14.04 beta 2 on a computer.

Ubuntu is pretty aggressive about their feature freezes, so I wouldn't hesitate to recommend you just install the beta now.

http://releases.ubuntu.com/14.04/

**Comment by scpeters** [comment]
I'm using indigo on Ubuntu 13.10, which is already released.

**Comment by adolfo-rt** [comment]
> On another note, I'd like to suggest all manifest.xml, stack.xml, and dual-CMake files be cleaned up/removed from the Indigo branch so as to remove all rosbuild support, since Fuerte users should be hopefully migrating by this release. Thoughts?

We should definitely drop all rosbuild support artifacts before releasing into Indigo.

The only thing we should watch out for are pending API braking changes. Along these lines: I have not merged in Hydro my pending transmission parsing changes, because #141 touches some internal APIs that were broken (see [here](https://github.com/ros-controls/ros_control/pull/141/files#diff-12) for actual code changes). The only user of this API that I know of (other than #141 itself) is `gazebo_ros_control`, which needs to be patched. I think this is the main blocker for releasing into Indigo.

I have low availability until mid-May, and although I might be able to sort this out before such a date, I can't guarantee it ATM.

**Comment by scpeters** [comment]
Bump for indigo release, since it's blocking gazebo_ros_pkgs. We're considering splitting gazebo_ros_pkgs into separate git repositories to make releases of gazebo_msgs, gazebo_ros, and gazebo_plugins separately from gazebo_ros_control (https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179).

**Comment by davetcoleman** [comment]
I'll work on releasing it this weekend

**Comment by adolfo-rt** [comment]
I'm in the middle of two weeks of heavy work travel. @davetcoleman, I greatly appreciate your offer, I believe I left all repos ready for release.

**Comment by davetcoleman** [comment]
rqt_plot and perhaps others from https://github.com/ros-visualization/rqt_common_plugins seem to be blocking ros_control from being released. However, it appears it will be released next Indigo update.  @dirk-thomas is this correct?

I have just released [realtime_tools](https://github.com/ros-controls/realtime_tools/issues/11) and [control_toolbox](https://github.com/ros/rosdistro/pull/4226), and will be releasing the rest in the next day or two.

**Comment by davetcoleman** [comment]
[ros_control](https://github.com/ros/rosdistro/pull/4227) and [ros_controllers](https://github.com/ros/rosdistro/pull/4228) have both been released into indigo. 

There are still other PRs and issues to get into Indigo, but at least now we will not be holding up the new distro release.

**Comment by scpeters** [comment]
Thanks for all your hard work!

**Comment by davetcoleman** [comment]
Most of the credit goes to @adolfo-rt

**Comment by yaronv** [comment]
Does anyone know when the indigo release is scheduled to? the exact date.
Thanks!

**Comment by davetcoleman** [comment]
ros_control issues isn't the most relevant place to ask that question. and aside from this month, no.

**Comment by adolfo-rt** [comment]
We have an Indigo release, yay!.

**Comment by yaronv** [comment]
Really? it's announcment is not on their site yet

**Comment by davetcoleman** [comment]
I think @adolfo-rt was referring to ros_control being released into indigo, not Indigo being released itself.

**Comment by adolfo-rt** [comment]
Hey @yaronv, I am indeed referring to the release of ros-controls into the indigo build farm, which is the subject of this issue.

The official release of ROS Indigo (the distribution) will be announced on ros-users@code.ros.org once it takes place. You can also follow ROS release related discussions by subscribing to the ros-release@lists.ros.org mailing list.
