### ISSUE TITLE
Convert CMake tests to <test_depend>

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#157]
http://wiki.ros.org/catkin/package.xml#Build.2C_Run.2C_and_Test_Dependencies

Me:

> Shouldn't this be <test_depend> ?

Adolfo:

> It actually should, yes. At least in Indigo since the merge of ros/catkin#612. This code was written for Hydro, and by that time <test_depends> were being ignored by the buildfarm. My suggestion would be to merge the PR first, and then do a pass across the whole of ros_control to fix build/test dependencies.

**Comment by davetcoleman** [comment]
Cleaning up issues.

**Comment by adolfo-rt** [comment]
This issue, although somewhat old, has in fact not been addressed. I would keep it open as a reminder of pending tasks.

**Comment by bmagyar** [comment]
This has been long resolved.
