### ISSUE TITLE
controller_manager: spawner blocks indefinitely if manager shuts down first

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_control#160]
Currently when bringing up a spawner and a controller manager, the spawner blocks on shutdown if the controller manager is shut down first. This wastes a lot of time during testing when bringing up the spawner and manager at the same time in simulation.

Instead, there should be a shorter timeout or a more reliable way of determining if the controller manager is still running.

**Comment by davetcoleman** [comment]
I've noticed this annoying issue as well

**Comment by normanhendrich** [comment]
Well, Stu Glaser told me about the "--shutdown-timeout" option. For me, it mostly fixes the symptoms, namely Gazebo taking forever to shut down:

 <node name="spawn_oro_gazebo_head_controller"
    pkg="controller_manager" type="spawner" respawn="false" output="screen" ns="oro"
    args="head_controller --shutdown-timeout 1" >
  </node>

**Comment by fmessmer** [comment]
As I had similar problems (i.e. gazebo taking forever to shutdown), I added the `--shutdown-timeout` option as well. While it does reduce the `wait_for_service` timeouts, it doesn't seem to solve the problem once and for all.
Still the problem occurs that the spawners do not terminate properly to `Ctrl+C`

```
...
[gazebo-2] killing on exit
Segmentation fault (core dumped)
[sensorring/joint_state_controller_spawner-22] escalating to SIGTERM
[WARN] [WallTime: 1421665850.575741] [5.776000] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 1 second(s).
[base/base_controller_spawner-13] escalating to SIGTERM
[WARN] [WallTime: 1421665850.945231] [5.776000] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 1 second(s).
[base/joint_state_controller_spawner-12] escalating to SIGTERM
[WARN] [WallTime: 1421665851.050191] [5.776000] Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 1 second(s).
[gazebo-2] escalating to SIGTERM
...
```

When I comment [this line](https://github.com/ros-controls/ros_control/blob/indigo-devel/controller_manager/scripts/spawner#L60) in the spawner, I face this problem only on much rarer occasion....
So removing the sleep does not completely seem to solve it, but it's way better without it ;-)
What was the original intention for this sleep? Do we still need it?

**Comment by lgeo3** [comment]
up ?

removing the sleep line in controller_manager/spawner (as highlight by @ipa-fxm) help me to get a faster/cleaner ctrl-c stop. What do you think ?

**Comment by corot** [comment]
Facing this problem after migrating to Kinetic. :see_no_evil: 
I can confirm that removing the sleep works

**Comment by jacknlliu** [comment]
I had a similar problem with ROS kinetic. Is it fixed?

**Comment by bmagyar** [comment]
Check #284 guys, if you could do some more testing on your respective platforms that'd be very helpful.
