### ISSUE TITLE
Register plugin under a group

### ISSUE THREAD

**Issue by dirk-thomas** [ros-controls/ros_control#162]
Please register the capabilities plugin under a group rather then the root of the plugin list. Similar as this: https://github.com/ros-visualization/rqt_robot_plugins/blob/772485a364203d9d0f9a8ff57870e89e2bfa42ce/rqt_robot_steering/plugin.xml#L7

I am not sure which group fits the plugin best - may be "Robot Tools"?

**Comment by adolfo-rt** [comment]
Robot Tools sounds fine. @kphawkins, do you also agree with the proposed group?.

**Comment by kphawkins** [comment]
Sounds fine to me. Maybe whereever Robot Monitor is stored. A novice user would probably associate controller loading with low level functionality.

**Comment by dirk-thomas** [comment]
That is the group `robot monitor` is in: https://github.com/ros-visualization/rqt_robot_plugins/blob/772485a364203d9d0f9a8ff57870e89e2bfa42ce/rqt_robot_monitor/plugin.xml#L8

**Comment by kphawkins** [comment]
Cool, then I'm okay with it.
