### ISSUE TITLE
missing inline in header file 

### ISSUE THREAD

**Issue by enricovillagrossi** [ros-controls/ros_control#182]
Dear all,
looking in folder joint_limit_interface/... I have notice the missing of "inline" keyword for all the functions defined in header file. This can cause linking error, such as "multiple definition of ..." if you have a multiple inclusion of the same header file. Could you fix this bug?
Thank you.
Enrico

**Comment by adolfo-rt** [comment]
I took a quick look at the package, and I saw that most (all?) methods are defined inline with their declaration, case in which the inline hint is implicit and not needed. The `inline` keyword is required if a function/method is not templated, its declaration and definition are separate, and its definition is in the header.

In case I'm missing something here, could you post the exact compilation errors, including the files and line numbers that are failing?. Also the branch of `ros_control` you're building and the compiler/version would help.

**Comment by enricovillagrossi** [comment]
I try to better explain: I'm using the function getJointLimits(...) defined in joint_limit_interface/joint_limits_urdf.h the linker error is: 

multiple definition of `joint_limits_interface::getJointLimits(boost::shared_ptr<urdf::Joint const>, joint_limits_interface::JointLimits&)'

the inline keyword (as expected) allows to prevent the error of multiple inclusion generated from the linker. The complier is g++ with the C++11 std.

Enrico

**Comment by adolfo-rt** [comment]
What gcc version are you using?. I still wonder why I had not seen this before. Does the `joint_limits_interface` test suite successfully build and link on your setup without the changes you propose?.

**Comment by enricovillagrossi** [comment]
I'm using gcc v4.6, if you want to reproduce the error you can create: 

your_header.h 

#ifndef **YOUR_H**
#define **YOUR_H** 

#include <joint_limits_interface/joint_limits_urdf.h>

#endif

and then include your_header.h in two different header file. 
Your linker will find the multiple definition of all the functions defined in the joint_limits_urdf.h...
Let me know if you are able to reproduce the error.

Enrico

**Comment by adolfo-rt** [comment]
#183 should have fixed it. Let me know if problems persist.

**Comment by enricovillagrossi** [comment]
Thank you!
Enrico
