### ISSUE TITLE
Release 0.7.3 into hydro and 0.9.0 into indigo

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#187]
I'm planning on making a simultaneous release of `ros_control` into hydro (0.7.2 → 0.7.3) and indigo (0.8.2 → 0.9.0) early next week. Prerelease tests are passing on both branches. If there are any bugfixes that you would like to see in these releases, please let me know.

**Comment by davetcoleman** [comment]
+1

:-) I just want a mode switching controller...

**Comment by adolfo-rt** [comment]
> :-) I just want a mode switching controller...

That'll have to wait a bit more. The switching controller won't land in this release.

**Comment by bmagyar** [comment]
Releasing was successful, and happened quite a long time ago :) 

Closing...
