### ISSUE TITLE
Standard way to get URDF / KDL Chain / Robot Model from Hardware Interface?

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_control#19]
I'm adapting the `tff_controller` from www.github.com/jbohren-forks/pr2_doors and like most cartesian controllers, it requires a kinematic model to do it's thing. The old PR2 controller would get the robot model from the old `pr2_mechanism_model` but the neither `hardware_interface::HardwareInterface` nor `hardware_interface::JointCommandInterface` have a standard interface for getting a robot model. So for now, I'm just pulling it out of a controller-specific parameter.

Whether this is a KDL model or an URDF model doesn't really matter, but is such an interface something that the ros_control team is considering?

**Comment by wmeeusse** [comment]
We purposefully left the robot description out of the interfaces; the new controllers fetch the robot description from the parameter server and parse it into a robot model. In the new design, the hardware interfaces are very minimalist, and only provide access to sensors and actuators, but not contain any properties (inertia, joint limits, etc) of the hardware.

**Comment by jbohren** [comment]
Cool, thanks! So is it reasonable to use a controller-namespace-local URDF parameter, or should a metaparameter (name of another parameter) be passed into the controller to reduce copying the URDF all over the place?

**Comment by wmeeusse** [comment]
Since the controllers are in a namespace, and ros does not support a parameter like '../robot_description', the only ways to get access are:
- create a new nodehandle inside the init of the controller, and get the 'robot_description' parameter
- copy the robot description into the controller namespace

I've been using the first option for the new controllers.

**Comment by jbohren** [comment]
Maybe using [ros::param::search()](http://ros.org/doc/groovy/api/roscpp/html/namespaceros_1_1param.html#aa2f629df62708ef810e34bad6c7ef332) would be good, and then report via `ROS_INFO()` about where it finds the URDF?

**Comment by wmeeusse** [comment]
Cool, I didn't know about the search function. That's a possibility too. So it looks like there are plenty of ways for developers of controllers to get access to the robot description. We could document some of them as 'best practices' on the wiki.

**Comment by jbohren** [comment]
As a note here's using `ros::param::search()` in the TFF controller: https://github.com/jbohren-forks/ros_controllers/commit/5c2319a34af27111b884f52c0f8e9ce27afab862
