### ISSUE TITLE
Limit Interface to ensure thrusters don't get overdriven

### ISSUE THREAD

**Issue by compiaffe** [ros-controls/ros_control#192]
Hey ho,

I'm trying to use your great framework for controlling an AUV with 5 controllable DOF (all but roll).

I am a little bit worried about the controller producing a signal with too quick changes in command. 
i.e. t=1, command=+100; t=2, command= -100 

Is the joint limit interface the right tool to prevent this? If not is there anything available, short of checking the derivative of the command signal and applying a limit.

Cheers,

Rapha

**Comment by adolfo-rt** [comment]
Rapha,

The issue tracker is the place for reporting bugs, proposing features, keeping track of pending tasks and the like; but it's not the place for asking user questions. For that we have the [robot control SIG](https://groups.google.com/forum/?fromgroups#!forum/ros-sig-robot-control). If you post your question there, I'll make sure to reply with an answer.

Thanks in advance.
