### ISSUE TITLE
controller_manager spawner hangs on shutdown in launch file with gazebo

### ISSUE THREAD

**Issue by mitchellwills** [ros-controls/ros_control#195]
Recently I have encountered an issue where the controller_manager spawner does not shutdown cleanly when run from a launch file. I am running ROS Indigo on Trusty.

I have a launch file that launches gazebo with a ros_control plugin as well as the robot_description and a few other things. Everything starts up fine, but when I try to shutdown the launch file by sending roslaunch a SIGINT on the terminal the controller_manager spawner process hangs. roslaunch tries to kill the process and fails. I then get messages indicating that it is escalating to a SIGTERM and then SIGKILL (which finally kills it). If I run the launch file, but comment out the controller spawner everything launches and shuts down cleanly. If I run the launch file without the spawner and then run the spawner in another terminal it runs and shuts down cleanly (even if I kill the launch file which runs the controller manager first). Running the spawner in the launch file also exhibits the same behavior if I run roscore seperatly.

From checking out the source and adding some print statements I believe that the program is getting stuck on the wait_for_service call for the unload controller service (https://github.com/ros-controls/ros_control/blob/indigo-devel/controller_manager/scripts/spawner#L65). Even if I reduced the shutdown time to one second the process still hangs. I'm not sure if this is potentially an issue with rospy and not ros_control, but I don't know enough about rospy to be sure.

**Comment by adolfo-rt** [comment]
The `--shutdown-timeout` option was added ina recent PR to address the issue you mention.

A shot in the dark here: We currently use rospy's shutdown hook ([source](https://github.com/ros-controls/ros_control/blob/indigo-devel/controller_manager/scripts/spawner#L172)), which should allow service calls and ros parameter queries. You could try using Python's `signal` module to trigger the shutdown hook and see if matters improve, some thing like:

``` python
import signal
def shutdown(signum, frame):
  # do stuff
  rospy.signal_shutdown("shutdown message")
signal.signal(signal.SIGINT, shutdown)
```

**Comment by mitchellwills** [comment]
Hmm I just realized that in my testing I was changing the global variable, but the argument parser was replacing it with the default value (30). Using the shutdown-timeout option works as expected.
Thanks

**Comment by mikepurvis** [comment]
I'm getting this too.

Specifying `--shutdown-timeout` fixes it for me, but this seems like a hack. I'm wondering if the spawner could detect when it has been run as a node, and automatically select a 1.0 second timeout as the default in that scenario?

This am-I-a-node check could be as simple as checking whether it was passed a `__name` parameter.

**Comment by adolfo-rt** [comment]
I don't quite understand the am-I-a-node check.

The problem occurs when the controller manager dies before the spawner, thus killing the service servers. One solution would be to periodically check within the spawner script that the controller manager it talks to is up and running. If the controller manager dies, the spawner should not stop and unload controllers when shutting down. One might even go as far as shutting down the spawner as well, as it no longer serves a purpose.

**Comment by mikepurvis** [comment]
That solution would also work.

The problem is basically guaranteed to manifest when the spawner is launched as a node because it means that it will get killed at the exact moment that the manager goes down, so it will _never_ get to unload its controller the way it wants to.
