### ISSUE TITLE
joint state controller not found error

### ISSUE THREAD

**Issue by Exception4U** [ros-controls/ros_control#196]
when I try to run my husky robot project I get the message 

[ERROR] [1420708232.424065268, 0.039000000]: Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist.
[ERROR] [1420708232.424169592, 0.039000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types

How to go forward ?

**Comment by adolfo-rt** [comment]
The issue tracker is not the right place for troubleshooting questions like this one. Please use the [robot control SIG](https://groups.google.com/forum/#!forum/ros-sig-robot-control) for that purpose. If you do so, make sure to provide a more complete summary of your problem.
