### ISSUE TITLE
Controller loading hangs

### ISSUE THREAD

**Issue by jlamyi** [ros-controls/ros_control#202]
Hi! My problem is that every time I load my controller, it hangs at "Loading controller: xxxx". Does anyone what is the issue for this? Thanks

**Comment by adolfo-rt** [comment]
Please use the [robot control SIG](https://groups.google.com/forum/?fromgroups#!forum/ros-sig-robot-control) for non-development related questions. Also, please check the list archives, as your question might have already been answered before. Take a look at [this question](https://groups.google.com/forum/#!topic/ros-sig-robot-control/bjBKzFBMXTk).
