### ISSUE TITLE
Switch default ros_control branch to jade-devel

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#216]
I can do this as a maintainer, just wanted to check with @adolfo-rt and others before doing it.

**Comment by adolfo-rt** [comment]
We'll do it once the jade branch is ready for release, which has taken some time. Because we're breaking APIs in places, I don't want to send the message that things are ready before they really are.

**Comment by davetcoleman** [comment]
Jade has been released, right? I'll switch the branches...
