### ISSUE TITLE
Adding new maintainers

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#219]
I would be interested in having other people share the load of merging PRs and making releases. There are currently two persons, @efernandez and @bmagyar that have offered to help with some of these tasks.

Because I'm a member and not an owner of this organization, I cannot grant them member access. So, could one of the owners please take action? (add me as an organization owner and/or add them as members).

Pinging current owners: @ahendrix, @davetcoleman, @tfoote, @wjwwood.

TIA

**Comment by wjwwood** [comment]
@adolfo-rt I promoted you to a team manager, which should allow you to add people to the `ros_control` team on the organization. Let me know if that is sufficient for you to add the user's in question.

**Comment by bmagyar** [comment]
Thanks for the support!

**Comment by efernandez** [comment]
Thanks!

@adolfo-rt Let us know when you make us members.

**Comment by adolfo-rt** [comment]
Only organization owners can send invitations for others to join. That part at least I still cannot do.

**Comment by wjwwood** [comment]
@adolfo-rt can you check to make sure you cannot invite them to the `ros_control` team? This note in the GitHub interface leads me believe that you should be able to since I made you a team maintainer:

<img width="298" alt="screen shot 2015-12-01 at 8 48 13 am" src="https://cloud.githubusercontent.com/assets/100427/11507337/680e2dac-9808-11e5-99e0-f837a5d3ae7f.png">

**Comment by adolfo-rt** [comment]
[A team maintainer](https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/) _should_ be able to add/remove members, but when I try to [add a new member](https://help.github.com/articles/adding-organization-members-to-a-team/), I get the following:

![gh](https://cloud.githubusercontent.com/assets/1128028/11538651/31e2cfc8-9923-11e5-8168-e721ffee5e02.png)

See how users are grayed-out, and the message stating `Only organization owners can Send Invitations`. No clue why I'm getting this.

**Comment by wjwwood** [comment]
Weird. I guess you can add/remove people to the team but not the organization? Either way I just sent them invitations.

**Comment by efernandez** [comment]
Thanks @adolfo-rt @wjwwood

**Comment by bmagyar** [comment]
Thanks guys!

**Comment by adolfo-rt** [comment]
Much appreciated @wjwwood
