### ISSUE TITLE
Could ControllerBase::starting() and ::stoping() return true or false depending on success?

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_control#22]
If a controller fails to start or stop, it would be great to be able to report to the system that such a failure has occurred. This would be similar to the way that OROCOS RTT handles these events.

See the current behavior here (success always):
https://github.com/willowgarage/ros_control/blob/master/controller_interface/include/controller_interface/controller_base.h#L93

I know we shouldn't be re-inventing OROCOS, but this is one aspect that I think could prevent a lot of problems during controller switching.

Either this, or should an exception be thrown?

**Comment by wmeeusse** [comment]
Can you give some examples of situations where you want start/stop to fail?  One way to look at start/stop is that it's the first/last time the update loop runs, and the update loop can't ever fail.

**Comment by jbohren** [comment]
(: well I'd like it if start/stop never failed, but if there was some computation or resource that failed when [switching controllers](https://github.com/willowgarage/ros_control/blob/master/controller_manager/src/controller_manager.cpp#L99), it would be nice to be able to report the error, catch it, and then try to stop everything else cleanly.

**Comment by wmeeusse** [comment]
Could you give some more specific examples? During the design discussions for the first controller manager, we decided that we didn't have a good use case for start/stop to fail, so I'm interested in more specific situations where this feature makes sense.

**Comment by jbohren** [comment]
Ah yeah. 

For `starting()`, consider you want to be able to refresh the parameters by restarting the controller. If the input is invalid, then start should fail.

For `starting()` and `stopping()` suppose you had a force sensor that was independent from the robot hardware interface, and you tried opening or closing the device, respectively, and that failed.

Basically, it just makes me nervous when there's a hook to arbitrary code, and there's no way to notify that a failure has occurred in that arbitrary code. Maybe I'm just thinking of using `starting()` and `stopping()` in incorrect ways?

**Comment by jbohren** [comment]
With respect to the parameter-update example (above) I think most of the controllers with `control_toolbox::PID`s in them actually do this.

**Comment by wmeeusse** [comment]
The examples you give fit really well in the init call, which has the ability to fail. Start/stop has to be realtime safe, so hitting the parameter server or initializing a device is probably going to break that requirement.  My mental model for start/stop is really as something that is part of the realtime update loop.

**Comment by wmeeusse** [comment]
One more comment: start/stop is guaranteed to happen in the same cycle as your first/last call to  update.

**Comment by jbohren** [comment]
Ah, I see. That makes sense then. Load/unload can fail, but start/stop shouldn't. (also I was wrong about the PID thing, init vs reset)

**Comment by wmeeusse** [comment]
Cool, glad to have that cleared up, thanks for the comments @jbohren!
