### ISSUE TITLE
No matching hardware interface found for 'hardware_interface/EffortJointInterface

### ISSUE THREAD

**Issue by top1944** [ros-controls/ros_control#280]
Hi：

I install ros-indigo-full and git the lastest code from https://github.com/ros-simulation/gazebo_ros_demos

But there are some FATALs  when I execute :

roslaunch rrbot_gazebo rrbot_world.launch

[FATAL] [1500900715.893432229, 0.001000000]: No matching hardware interface found for 'hardware_interface/EffortJointInterface
[FATAL] [1500900715.896409204, 0.001000000]: Could not initialize robot simulation interface

Why and how?

Thank you!

top@exbot:~$ roslaunch rrbot_gazebo rrbot_world.launch
... logging to /home/top/.ros/log/0a29bea4-70e7-11e7-9ae8-000c2998fc18/roslaunch-exbot-32446.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://exbot:36141/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [32461]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0a29bea4-70e7-11e7-9ae8-000c2998fc18
process[rosout-1]: started with pid [32474]
started core service [/rosout]
process[gazebo-2]: started with pid [32477]
process[gazebo_gui-3]: started with pid [32488]
process[urdf_spawner-4]: started with pid [32497]
Gazebo multi-robot simulator, version 2.2.3
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

spawn_model script started
Gazebo multi-robot simulator, version 2.2.3
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1500952328.870084474]: Finished loading Gazebo ROS API Plugin.
Msg Waiting for master
[1;[ INFO] [1500952328.872467516]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
32mMsg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.195.128
[INFO] [WallTime: 1500952328.945000] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1500952328.947870] [0.000000] Waiting for service /gazebo/spawn_urdf_model
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.195.128
[INFO] [WallTime: 1500952329.254544] [0.000000] Calling service /gazebo/spawn_urdf_model
[ INFO] [1500952329.357736680, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1500952330.498132295, 0.047000000]: Camera Plugin (robotNamespace = /), Info: Using the 'robotNamespace' param: '/'
[ INFO] [1500952330.578261932, 0.047000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1500952330.835698695, 0.047000000]: Laser Plugin (robotNamespace = /), Info: Using the 'robotNamespace' param: '/'
[ INFO] [1500952330.836056464, 0.047000000]: Starting GazeboRosLaser Plugin (ns = /)!
[INFO] [WallTime: 1500952330.845456] [0.047000] Spawn status: SpawnModel: Successfully spawned model
[ INFO] [1500952330.903900232, 0.047000000]: GPU Laser Plugin (ns = /) <tf_prefix_>, set to ""
[ INFO] [1500952330.909243914, 0.047000000]: Loading gazebo_ros_control plugin
[ INFO] [1500952330.922046723, 0.047000000]: Starting gazebo_ros_control plugin in namespace: /rrbot
[ INFO] [1500952330.938808495, 0.047000000]: LoadThread function completed
[ INFO] [1500952330.945822505, 0.047000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ INFO] [1500952330.990337224, 0.047000000]: Physics dynamic reconfigure ready.
[urdf_spawner-4] process has finished cleanly
log file: /home/top/.ros/log/0a29bea4-70e7-11e7-9ae8-000c2998fc18/urdf_spawner-4*.log
[FATAL] [1500952331.735253692, 0.047000000]: No matching hardware interface found for 'hardware_interface/EffortJointInterface
[FATAL] [1500952331.746082931, 0.047000000]: Could not initialize robot simulation interface

**Comment by bmagyar** [comment]
You should check out the Indigo version of `gazebo_ros_demos`, not the one from Kinetic.

[Here](https://github.com/ros-simulation/gazebo_ros_demos/blob/indigo-devel/rrbot_description/urdf/rrbot.xacro#L189) the interface looks ok for Indigo.

Nevertheless, next time please open issues on the directly related repositories first.
