### ISSUE TITLE
The constructor of ForceTorqueSensorHandle

### ISSUE THREAD

**Issue by sunbibei** [ros-controls/ros_control#282]
Hello, when I am using the hardware_interface::ForceTorqueSensorHandle, I confuse the self-define constructor. We should not want to change the data in this class, but the parameter list is asked a non-const pointer. The constructor define as follow, 
```
ForceTorqueSensorHandle(const std::string& name,
                          const std::string& frame_id,
                          double* force,
                          double* torque)
```
I don't known that whether it is a bug or not? Thank you.

**Comment by mathias-luedtke** [comment]
Good catch!

I don't see any reason for this. It is not bug, but a glitch w.r.t. const correctness.

**Comment by sunbibei** [comment]
Thanks your response, forgiving my poor English. there is a similar problem to the structure of ImuSensorHandle::Data. Thank you

**Comment by mathias-luedtke** [comment]
I have added a const ImuSensorHandle constructor as well.
We should not touch `ImuSensorHandle::Data` as it might be used elsewhere.

**Comment by sunbibei** [comment]
OK，i see. Thank you

**Comment by mathias-luedtke** [comment]
Let's keep this issue open until the PR was merged.
