### ISSUE TITLE
compilation error in joint_state_controller

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#3]
We're trying a rosmake in joint_state_controller and getting this error:

joint_state_controller.h:55:15: error: ‘JointState’ is not a member of ‘hardware_interface

The offending piece of code is:
std::vector<hardware_interface::JointState> joint_state_;

We don't see any JointState class within the hardware_interface namespace although we do see JointStateHandle and JointStateInterface in joint_state_interface.h

**Comment by wmeeusse** [comment]
Fixed. We just renamed JointState to JointStateHandle to be more specific.
