### ISSUE TITLE
Changes for Melodic

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_control#305]
Hello @ros-controls/ros_control team,

I'll be updating this issue with TODO-s for the Melodic release.
We are expecting some changes to break ABI and probably API even after the first release of Melodic. Some project have unlucky timing.

* [x]  class_loader headers migration
* [x]  pluginlib headers migration

These changes should affect `ros_control` and `ros_controllers`.
We are on the critical path for `gazebo_ros`, so anyone willing to do some migration is very welcome.

**Comment by mathias-luedtke** [comment]
ABI changes do not matter, it is quite hard to mix kinetic binaries with melodic binaries and the ABI won't be compatible anyway (C++14..).
There are no API breaks planned for melodic (?).
To get rid of the warnings, just the new header names should be used.
The new headers are already available for indigo and kinetic (shadow-fixed)..

**Comment by mathias-luedtke** [comment]
`ros_control` (itself) can be built and run with melodic using https://github.com/ipa-mdl/ros_control/commit/d63e833f290bda15ca0352cf1248a9eae30bdb0e
Travis: https://travis-ci.org/ipa-mdl/ros_control/jobs/356053823

(except `rqt_controller_manager`, which depends on `rqt_gui`)

**Comment by mathias-luedtke** [comment]
@bmagyar: I would suggest to release `ros_control` rather early, there are no blockers anymore.

**Comment by bmagyar** [comment]
Thanks for the heads up, it moves faster than I expected!

**Comment by bmagyar** [comment]
Initial release was made. I've just realised we are still using `boost::shared_ptr`. That should change to `std::shared_ptr` since starting from Melodic C++11 is default.
Any thoughts @ros-controls/ros_control ?

**Comment by mathias-luedtke** [comment]
>  since starting from Melodic C++11 is default.

C++14 (default of g++6.1 and above).

> That should change to std::shared_ptr

I would not change it directly.
This would force all dependent packages to branch for melodic.
Instead all pointers should get types in kinetic and melodic.
These can be switched to `std` pointers for new versions afterwards.

**Comment by mathias-luedtke** [comment]
@bmagyar: What convention do you prefer: `MyType[Const]Ptr` or `MyTypeShared[Const]Ptr`?
The latter is longer, but more specific wrt the shared ownership.

**Comment by bmagyar** [comment]
Personally the latter. The question is if we use already a few that follow
the shorter version. Urdf maybe? Or should we care at all?

**Comment by mathias-luedtke** [comment]
After a brief review:
URDF uses `MyType[Const]SharedPtr`.
In the ros-controls repositories `MyType[Const]Ptr` is used.

I would stick to the URDF convention, but keep the existing typedef as legacy entries with deprecation warning.

**Comment by bmagyar** [comment]
Agreed!
On branching: I think Melodic is a good candidate for most packages to branch anyways, I don't think it would be an issue.

**Comment by bmagyar** [comment]
I propose to add the typedefs to both branches and then change them to `std::shared_ptr` on Melodic ASAP.

I'd prefer to branch for `ros_controllers` too, there is an [issue in one of the tests ](https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/joint_trajectory_controller/test/joint_trajectory_controller_test.cpp#L190) which fails when compiled with C++11. 
I've added a fix that I think is elegant with a lambda [here](https://github.com/bmagyar/ros_controllers/commits/kinetic-devel) but I wouldn't enable C++11 on Kinetic nor would want to settle for a C-style type-enforcing.

**Comment by bmagyar** [comment]
#324
