### ISSUE TITLE
Graceful Handling of Exception / Error in Controlller Update

### ISSUE THREAD

**Issue by eacousineau** [ros-controls/ros_control#31]
Looking at [controller_manager/src/controller_manager.cpp](https://github.com/willowgarage/ros_control/blob/master/controller_manager/src/controller_manager.cpp#L90-L92) (7062d96) in ControllerManager::update(...), there does not seem to be a way to gracefully handle an error from the ControllerBase::updateRequest(...) function, either from catching exceptions or errors.

We think that this feature would be necessary for handling controller faults.

What would be a good error handling policy? Just stopping all controllers and setting an error state? (Like Orocos?)

**Comment by adolfo-rt** [comment]
I propose to close this issue, as a discussion with the same topic has been started [here](https://groups.google.com/forum/?fromgroups#!topic/ros-sig-robot-control/jaffUIsEgjk). The sig seems a better place to discuss such design considerations.
