### ISSUE TITLE
Cherry-pick #311 to Indigo and Kinetic

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_control#313]
...and perhaps Lunar?

#311

**Comment by mathias-luedtke** [comment]
> ...and perhaps Lunar?

This should be covered by kinetic.. (same code release to both)

**Comment by bmagyar** [comment]
#321   #322

**Comment by bmagyar** [comment]
I'll also push releases before closing this one

**Comment by bmagyar** [comment]
Releases done

https://github.com/ros/rosdistro/pull/17476
https://github.com/ros/rosdistro/pull/17475
https://github.com/ros/rosdistro/pull/17474
https://github.com/ros/rosdistro/pull/17473
