### ISSUE TITLE
realtime_tools are dependencies but not actually used

### ISSUE THREAD

**Issue by kjaget** [ros-controls/ros_control#320]
This is in the kinetic release tag release/kinetic/controller_manager/0.13.1-0 (and probably earlier as well).  The dependencies show up in CMakeLists.txt, package.xml and controller_manager.h in controller_manager and then also in ros_control/package.xml.

**Comment by bmagyar** [comment]
Nice catch, `controller_manager` probably doesn't need to depend on `realtime_tools`. The dependency in `ros_control` is there since that's a metapackage, `realtime_tools` is part of the `ros_control` bundle, every controller uses it for instance.

**Comment by kjaget** [comment]
Ah, makes sense. I missed the obvious point about ros_control being a meta-package.

**Comment by bmagyar** [comment]
Resolved in the referenced PR. Thanks for the report!
