### ISSUE TITLE
license in transmission_interface

### ISSUE THREAD

**Issue by pholthaus** [ros-controls/ros_control#326]
In [package.xml](https://github.com/ros-controls/ros_control/blob/melodic-devel/transmission_interface/package.xml) of transmission_interface, the license is specified as "modified bsd" while that seems to be the standard 3-clause BSD license as in the other packages in this repository as well. This can lead to problems when automatically parsing the file, such as
https://github.com/ros/ros-overlay/issues/567

Could you please unify the specification in package.xml to match the LICENSE file? Thank you

**Comment by bmagyar** [comment]
Thanks for the heads up, you are right!

Could you please parse the rest of the packages, also the ones at https://github.com/ros-controls/ros_controllers/ ? I'd like to resolve all at once.

**Comment by pholthaus** [comment]
There were only two package.xml files in each repository. I have created PRs fixing those two. HTH

**Comment by bmagyar** [comment]
Thank you!

**Comment by pholthaus** [comment]
Thank you for the quick response!

**Comment by pholthaus** [comment]
Could you please backport these fixes to kinetic?

**Comment by pholthaus** [comment]
I'm sorry to still commenting on this, but in kinetic-devel the issue still exists.

**Comment by bmagyar** [comment]
Sorted!

**Comment by pholthaus** [comment]
Perfect, thank you!
