### ISSUE TITLE
Unimplemented ControllerManager::getControllerSchedule method

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#33]
The [ControllerManager::getControllerSchedule](https://github.com/willowgarage/ros_control/blob/master/controller_manager/include/controller_manager/controller_manager.h#L171) private method is currently unimplemented. Is it a feature yet to be implemented?, if so, what purpose would it serve?.

**Comment by wmeeusse** [comment]
This is a leftover from the pr2 controller manager that got copy-pasted into the new controller manager. It should be fine to remove this method.
