### ISSUE TITLE
#define in system header netdb.h conflicts with transmission loader enum

### ISSUE THREAD

**Issue by jlack1987** [ros-controls/ros_control#333]
For some context, i'm trying to use boost asio in conjunction with the ros control RobotHw and there are of course transmissions involved. In trying to use both `transmission_interface` and `boost::asio`(via the `#include <boost/asio.hpp>` header), I have discovered a conflict between a `#define` in `netdb.h` which is used by boost and an enum defined in `transmission_loader.h`. Long story short if you have Boost installed there'll be a dependence on `netdb.h` and in that file is the following line,
```
# define NO_DATA	4	/* Valid name, no data record of requested`
```
and in `transmission_loader.h` there's this enum defined,
```
enum ParseStatus
  {
    SUCCESS,
    NO_DATA,
    BAD_TYPE
  };
```
which is a collision and you can't compile.

**Comment by bmagyar** [comment]
And you need this fixed on Kinetic? (It'd be easier to fix on melodic with
C++11.)

**Comment by jlack1987** [comment]
Yeah we are still using kinetic, will prob look to switch when the 18.04 stuff comes out. Out of curiosity how do you fix it without changing the name of the `NO_DATA` enum and possibly breaking compatability where ppl are using this? I have hacked around it by doing the following,
```
#undef NO_DATA
#include <transmission_interface/transmission_loader.h>
#define NO_DATA 4
```

**Comment by bmagyar** [comment]
I would use a class enum

http://en.cppreference.com/w/cpp/language/enum

Yes it is correct that it probably breaks downstream code but for Melodic
that is fine. That's what the changelog is for.

**Comment by mathias-luedtke** [comment]
> I would use a class enum

This would still lead to the naming conflict (?) as the the macro would get expanded in the enum declaration. However, this might the depend on the order.

I see three options:

1. alter the user's code: Do not include both, `#undef`, to not include all-in `asio.hpp`
2. rename enum options to be more specific 
3. get rid of the enum. it is protected anyway and `BAD_TYPE` could be expressed with an exception.

Options 2 and 3 break the (protected) API. Option 3 would solve this issue once and for all.

**Comment by mathias-luedtke** [comment]
> This would still lead to the naming conflict (?) as the the macro would get expanded in the enum declaration. However, this might the depend on the order.

http://cpp.sh/4275

For unscoped enums it depends on the order.  The `undef` trick possibly breaks the ABI (enum value gets changed to another value in certain source files), same for reordering.
With scoped enums the code will never compile.
