### ISSUE TITLE
Online trajectory replacement

### ISSUE THREAD

**Issue by tony1994513** [ros-controls/ros_control#343]
Dear sir,
I am a beginner in ROS, and I am very interested in online trajectory replacement. http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement . To the best of my knowledge, I think it use action_lib to send goal to the robot, but when I want to update the goal when robot is running, how should I do?  It seems actionlib only take a goal at a time. then what should i do to update the goal? Can you give a example of how to do it?  Thank you so much

**Comment by bmagyar** [comment]
You just send a new action. The new goal will preempt the old one and trajectory merging takes care of smooth transitions.
