### ISSUE TITLE
ros_control build issue using find_package()

### ISSUE THREAD

**Issue by leocorp96** [ros-controls/ros_control#344]
Hello, trying to build my package which depends heavily on ros_control stack tends to fail even though I created my project using "catkin_make my_project controller_manager other_packages". And I installed ros_control using "sudo apt-get install ros-kinetic-ros-control"

The error always points to any syntax that looks like this;
find_package(catkin REQUIRED COMPONENTS
  controller_manager)

However, the package builds successfully if I remove the "controller_manager" from my CMakeLists.txt;
find_package(catkin REQUIRED COMPONENTS)

Looks like we may have a bug of sorts.

**Comment by bmagyar** [comment]
`ros_control` has been stable for many years. From the fact of you closing the issue I suspect it was on your side.
