### ISSUE TITLE
Demangled symbol names for human readable output

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#36]
Would it make sense to store _demangled_ symbols when getting the **typeid** of a type?. I could prepare a patch that, when available (gcc >= 3.0), would use demangled names, otherwise fallback to mangled names.

The upside would be that log statements, inspection of controllers via command line (eg. controller_manager/list_controllers), etc. would be much easier to read, eg.

```
hardware_interface::VelocityJointInterface
```

instead of

```
N18hardware_interface22VelocityJointInterfaceE
```

**Comment by wmeeusse** [comment]
+1  I'd love to see that!
