### ISSUE TITLE
effort_controllers/JointVelocityController possibly incompatible units

### ISSUE THREAD

**Issue by kumpakri** [ros-controls/ros_control#363]
Me and many other people are having trouble using effort_controllers/JointVelocityController in scripts where other controllers works just fine. The models on which the JointVelocityController was used seemed to explode after launching simulation. Several solutions were found:

- decrease PID parameters
- increase inertial matrix
- increase mass

When I encountered the problem, I concluded the mass is suppose to be set in grams and that is the reason why my model blows up. The physics engine computes extreme values. But in the [Physical Properties tutorial](http://wiki.ros.org/urdf/Tutorials/Adding%20Physical%20and%20Collision%20Properties%20to%20a%20URDF%20Model),  they say the units are kilograms. 

Would it be possible to check if somewhere in the JointVelocityController is mistake that makes the units incompatible or what is the problem?

**Comment by mathias-luedtke** [comment]
Please note, this is the issue tracker for ` ros_control`, the one for `ros_controllers`  can be found [here](https://github.com/ros-controls/ros_controllers).

[effort_controllers/JointVelocityController](https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/effort_controllers/src/joint_velocity_controller.cpp) does not seem to convert any units, it just applies the PID control.
It does not use the mass or the inertial matrix (this is only used by gazebo).

It looks like you have tune your PID parameters properly..
I will close this issue now. If you need help with the configuration/tuning, please refer to [ROS answers](https://answers.ros.org/questions/).
Feel free to open a new issue for `ros_controllers` if needed.
