### ISSUE TITLE
cmake error compiling ros-kinetic

### ISSUE THREAD

**Issue by pmwenzel** [ros-controls/ros_control#376]
CMake Error at .../catkin_ws/devel/share/controller_manager/cmake/controller_managerConfig.cmake:148 (message):
  Project 'controller_manager_tests' tried to find library '-lpthread'.

Does anyone know how to fix it? Thanks.

**Comment by bmagyar** [comment]
Please use [ROS Answers](https://answers.ros.org/questions) for this type of enquiries.
