### ISSUE TITLE
ros_control and robots without joints/actuators/transmissions

### ISSUE THREAD

**Issue by Donny3000** [ros-controls/ros_control#38]
Hello All,

I have a question to pose to the developers of this stack regarding the overall architecture and it's application to robots in general.  I realize that this area is for issues regarding this stack, but I didn't know where to find a mailing list to present questions such as this. I will be more that willing to redirect this question to a mailing list if one is available. I've following the development of this stack for the last month and it looks very promising. I've also been looking at the source code to gain a better understanding of the architecture because I'm very interested in using this stack for my robot (specifically, a quadrotor), but I haven't been able to quite figure out how to apply it.  I understand that this stack is still in its primitive stages of development, but I like the generic control philosophy behind it and think that it could very well apply to quadrotor robot as well. Looking at the code I surmised that you should use the stack as follows:
1. Define robots hardware elements (imu, motor contollers, etc) using hardware_interface::HardwareInterface as the base class.
2. Define the robots overall hardware structure using hardware_interface::RobotHW as its base class
3. Define the controllers of the various hardware elements of the robot using controller_interface::Controller as their base class.

Would this be correct? I just want to make sure I understood the use of this stack correctly before digging deeper.

**Comment by wmeeusse** [comment]
Ya, that sounds right, and your application looks like a good match for this stack.

Good luck!

**Comment by adolfo-rt** [comment]
I didn't quite understand the "robots without joints/actuators/transmissions" part of the title. For a quadrotor you would at least expose the four propelling rotors as joints, right?, or does the hardware driver only expose a high level controller that operates in Cartesian space?. At any rate you should expose a set of joints, and optionally make transmissions and actuators explicit if this is required by your hardware setup.

**Comment by Donny3000** [comment]
Well, I wasn't planning on exposing the four propelling rotors as joints because it didn't seem appropriate to describe them as joints since they would be fixed. Likewise, the use of a transmission or actuator didn't seem appropriate for a quadrotor application as well.  But, I probably have a poor understand/application of the terminology (and how the terminology applies to aerial vehicles in general).  My thought was to create a hardware interface for the Electronic Speed Controllers, IMU, etc, and create a controller that would operate in Cartesian Space, like you mentioned, for control of the yaw/pitch/roll of the quadrotor.  It made sense in my head, but maybe I need a few more pieces (joints/transmissions/actuators) to fully implement the control system.

**Comment by adolfo-rt** [comment]
If the Electronic Speed Controllers control the rotor speeds, you can model rotors as velocity-controlled joints. A rotor interacting with the air is not that different from a wheel interacting with the ground. I don't know about aerial robots, but for wheeled robots, wheels are explicitly modeled as joints.
