### ISSUE TITLE
How to create FollowJointTrajectory action server?

### ISSUE THREAD

**Issue by pawelwisniewski9603** [ros-controls/ros_control#381]
Hi!
I`m Paweł and i`m new in Ros. I`m doing my final project for my university(kuka kr150 r3100 prime and ros). I did a URDF file - works fine. Next step was MoveIt - i see my robot in rviz also i can move it. But next, i need to have propertly configured FollowJointTrajectory action service. And i spend few day to do this - and still nothing. Maybe someone hace a good tutorial/video how to create it? i loose my faith in this project...:(
I would be very grateful for Your help,
Pawel

**Comment by bmagyar** [comment]
For those arms I'd expect some drivers to be around already. Please have a look around here: https://github.com/ros-industrial/industrial_training and in the ros industrial packages in general. 

Also please refrain from opening issues on the github page in the future unless you have actual bugs to report. ROS Answers is the platform where you can ask away anything about usage and setup and expect fast response from peers: https://answers.ros.org/questions/

Have fun!
