### ISSUE TITLE
deadcode - redundant

### ISSUE THREAD

**Issue by danielwangksu** [ros-controls/ros_control#385]
https://github.com/ros-controls/ros_control/blob/cc4b2aa117c27a4f29dcd673f9ee96a9158262aa/transmission_interface/src/transmission_parser.cpp#L160

https://github.com/ros-controls/ros_control/blob/cc4b2aa117c27a4f29dcd673f9ee96a9158262aa/transmission_interface/src/transmission_parser.cpp#L226

**Comment by mathias-luedtke** [comment]
Yes, both lines could be omitted, but I don't see an urgent need to do so.
Of course, a PR is welcome.
