### ISSUE TITLE
coverity report Call to "unloadController" might sleep while holding lock "guard.m"

### ISSUE THREAD

**Issue by danielwangksu** [ros-controls/ros_control#386]
Call to "unloadController" might sleep while holding lock "guard.m". Is the expected behavior?
https://github.com/ros-controls/ros_control/blob/cc4b2aa117c27a4f29dcd673f9ee96a9158262aa/controller_manager/src/controller_manager.cpp#L665-L678

**Comment by mathias-luedtke** [comment]
> Call to "unloadController" might sleep while holding lock "guard.m". Is the expected behavior?

Yes. This is part of the RT / non-RT decoupling.
