### ISSUE TITLE
controller_manager_interface (similar to pr2_controller_manager_interface.py)?

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#4]
Is there a plan to port pr2_controller_manager_interface.py and pr2_controller_manager (the python script in the scripts folder) to this new controller_manager infrastructure?

We see a spawner but not anything more in controller_manager/scripts.

**Comment by wmeeusse** [comment]
Yes, these scripts will also exist for the new controller manager. I copied the old scripts into the new controller manager package, and did the basic string replacement porting work. But obviously, these scripts still need to get tested.

**Comment by wmeeusse** [comment]
Fixed
