### ISSUE TITLE
Remove _tests packages from metapackage

### ISSUE THREAD

**Issue by matthew-reynolds** [ros-controls/ros_control#409]
Following up from https://github.com/ros-controls/ros_control/pull/404#discussion_r363080746:

The `combined_robot_hw_tests` and `controller_manager_tests` packages should not be released and should not be dependencies of the metapackage. If they offered a framework for testing plugins/3rd party code, they would have a reason to be released, but as implemented they are essentially just more tests for their respective packages.

Steps to take:
 - [x] Remove these packages from the `ros_control` metapackage, certainly in Noetic but ideally also in Kinetic and Melodic (Done in #411)
 - [ ] ~In Noetic, do not release these packages~ Edit: Nevermind, let's release these as before in case anyone leverages them for their own tests.

**Comment by mateus-amarante** [comment]
Shouldn't those *_tests packages be test dependencies of the meta package? Like:

```xml
<test_depend>controller_manager_tests</test_depend>	
<test_depend>combined_robot_hw_tests</test_depend>
```

**Comment by matthew-reynolds** [comment]
`rosdep` doesn't distinguish between any types of dependencies, it just globs everything together (See [here](https://github.com/ros-infrastructure/rosdep/blob/d1784da592310c7ad8e649530200cdf957a87afc/src/rosdep2/rospkg_loader.py#L143)). `rosinstall_generator` does the same (See [here](https://github.com/ros-infrastructure/rosinstall_generator/blob/b175367a4d39473c77871c91719a39e277d26b64/src/rosinstall_generator/distro.py#L89)).

Since there's no ability to filter out test dependencies, some potentially very heavy dependencies (ie gazebo) will be pulled in. Excluding test depends from the metapackage (And ultimately re-structuring some tests into dedicated packages which can also be excluded) makes it much more convenient for non-desktop installs.

**Comment by matthew-reynolds** [comment]
Also, I forget who but someone brought up that it's still worthwhile to release the tests in case anyone wants to build their own tests on top of them, even if they're not part of the metapackage proper. So I'm going to remove the second item from this TODO and close this issue, as it is complete. Heads up @bmagyar
