### ISSUE TITLE
Harmonize how variables are quoted in log statements.

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#42]
This is really nitpicking, but I'm a big fan of consistency.

In the hardware_interface and transmission_interface packages, joint, actuator, and transmission names are printed **[between square brackets]**, while in the controller_manager package, controller names are printed **'between single quotes'**. I'd like to harmonize this, so the same delimiters are used throughout the whole of ros_control's log statements. I'll leave the choice to the original developers, but offer to provide a patch implementing the fix.

**Comment by wmeeusse** [comment]
+1 for consistency.  I don't have a strong opinion on what the convention ends up being, so pick whatever you like best.

**Comment by adolfo-rt** [comment]
If I can have it my way, I choose single quotes. Patch will follow shortly
