### ISSUE TITLE
Moving to Python 3

### ISSUE THREAD

**Issue by lepalom** [ros-controls/ros_control#459]
I'm trying to build ros-controls with buster and pure Python3. I have found that the shebangs should be changed (maybe) and to run rqt_controller_manager I have to change this line:

```
--- a/rqt_controller_manager/src/rqt_controller_manager/controller_manager.py
+++ b/rqt_controller_manager/src/rqt_controller_manager/controller_manager.py
@@ -44,7 +44,7 @@ from controller_manager_msgs.utils\
     import ControllerLister, ControllerManagerLister,\
     get_rosparam_controller_names
 
-from update_combo import update_combo
+from .update_combo import update_combo
 
 
 class ControllerManager(Plugin):

```

I'm not Python expert but it solves it. Please, could you check it?

Maybe it have some relation to #455

**Comment by bmagyar** [comment]
This should be fixed by the last release, the debian buildfarm has been having some issues lately but please give it a go from ubuntu focal ;)

**Comment by robogeekcanada** [comment]
Looks like this hasn't been corrected for Ros Noetic yet. l recently tried `sudo apt-get install ros-noetic-ros-control ros-noetic-ros-controllers` and had to complete the same fix to make it work.

```
-from update_combo import update_combo
+from .update_combo import update_combo
```

**Comment by bmagyar** [comment]
It has been fixed, look here: 
https://github.com/ros-controls/ros_control/blob/noetic-devel/rqt_controller_manager/src/rqt_controller_manager/controller_manager.py#L47

Update your installation
