### ISSUE TITLE
Loading joint_state_controller/JointStateController stop

### ISSUE THREAD

**Issue by nimerf** [ros-controls/ros_control#477]
Hi everyone,,

I try to use ros_control to control motors so I made test to see if I'm able to do it. 
I write a launch file but when launch it, it stop at loading controller without error : 

![error](https://user-images.githubusercontent.com/53628384/93665756-66266300-fa79-11ea-8ab2-7443bbc255d3.jpg)

Here is the launch file : 
![Launch](https://user-images.githubusercontent.com/53628384/93665856-2744dd00-fa7a-11ea-9816-2f9a7787b8bc.jpg)

And controller : 
![Controller](https://user-images.githubusercontent.com/53628384/93665858-290ea080-fa7a-11ea-851e-824c3388aca4.jpg)

What am I doing wrong ?

**Comment by mateus-amarante** [comment]
Could you provide more details about `ROBOT_hardware_interface_node`? At first glance, I would suspect the problem is there. Are you calling `ros::spin()` or periodically calling `ros::spingOnce()`, so the controller manager services callbacks are called?

**Comment by nimerf** [comment]
Yes there was a mistake this the ros::spin(). I mess up things a little !
