### ISSUE TITLE
joint_states/effort goes to zero when published a torque using effort_controllers/JointGroupEffortController in Gazebo

### ISSUE THREAD

**Issue by amjack0** [ros-controls/ros_control#487]
I am using `effort_controllers/JointGroupEffortController` wit ur5 arm in Gazebo. I set up my controller (interface etc) like this,

[UR5 package Link](https://github.com/amjack0/universal_robot_effortController)

My controller yaml looks like this,

`arm_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
   - shoulder_pan_joint
   - shoulder_lift_joint
   - elbow_joint
   - wrist_1_joint
   - wrist_2_joint
   - wrist_3_joint`

I run `roslaunch ur_gazebo ur5.launch` and I can see my controller topic `/arm_controller/command`
So, When I publish `rostopic pub` a desired torque of lets say 60 Nm on effort_controllers/JointGroupEffortController. Then it would go to 60 Nm then goes to Zero and the to 60 Nm and again to zero. 

I checked my `ur5.urdf.xacro` for friction, damping, safety controller and limits. Not sure what's wrong.

I plot joint_states/efforts to analyze this issue. This issue is seen for every joint. (In the plot, only shoulder_lift_joint is analyzed.)
Plot of the joint state effort looks like this, [rqt plot](https://raw.githubusercontent.com/amjack0/custom_ros_action_server/master/Screenshot%20from%202020-12-30%2019-28-36.png)

ROS Melodic , 18.04
gazebo-9.0.0
Universal Robot (UR5) `https://github.com/ros-industrial/universal_robot/tree/melodic-devel

**Comment by bmagyar** [comment]
Please don't spam over multiple repos.
Closing in favour of https://github.com/ros-controls/ros_controllers/issues/548
