### ISSUE TITLE
can't find ros control

### ISSUE THREAD

**Issue by Omunkhuush** [ros-controls/ros_control#499]
CMake Error at /home/munkhuush/catkin_ws/devel/share/controller_manager/cmake/controller_managerConfig.cmake:113 (message):
  Project 'controller_manager' specifies
  '/home/munkhuush/catkin_ws/src/ros_control/controller_manager/include' as
  an include dir, which is not found.  It does neither exist as an absolute
  directory nor in
  '/home/munkhuush/catkin_ws/src/ros_control/controller_manager//home/munkhuush/catkin_ws/src/ros_control/controller_manager/include'.
  Check the issue tracker
  'https://github.com/ros-controls/ros_control/issues' and consider creating
  a ticket if the problem has not been reported yet.

**Comment by bmagyar** [comment]
you could save yourself a whole lot of trouble if you used apt instead:
```apt-get install ros-noetic-ros-control ros-noetic-ros-controllers```
or just fix your build setup.

For questions like this please don't use the issue tracker but ask for help at https://answers.ros.org/questions/ .
