### ISSUE TITLE
Order of update calls of individual controllers when Controller Manager's update is called

### ISSUE THREAD

**Issue by RohanBampal** [ros-controls/ros_control#500]
Hi,

I want to know if we can know (or modify) the execution order of controller's `update()` call when controller manager's `update()` is called.

I have some controllers which uses data generated from another controller. If I can somehow make the controller generating the data update first, then other controllers need not wait for the next `update()` call of the controller manager.

Is there any existing functionality for this?

**Comment by bmagyar** [comment]
Chained controllers are a new feature in ros2_control, please head over there ;)
