### ISSUE TITLE
Tutorial for using ros_control in Python3

### ISSUE THREAD

**Issue by bhomaidan1990** [ros-controls/ros_control#502]
Hi,

- Is it possible please to provide a small tutorial on how to use the functionalities of this library using python3?
- Because the only tutorial I can find is in C++.

Thanks in advance.

**Comment by bmagyar** [comment]
What would you like to use in python3? Afaik we only have a python interface for the controller manager but we don't support writing controllers in python.

**Comment by bhomaidan1990** [comment]
So it is not possible to rewrite my robot [hardware interface](https://github.com/kth-ros-pkg/yumi/blob/egm_modifications/yumi_hw/include/yumi_hw/yumi_hw.h) in python instead of C++?
