### ISSUE TITLE
ros_control error during Catkin_make of franka_ros package on Arch Linux realtime kernel (Franka Emika Panda Robot)

### ISSUE THREAD

**Issue by ruturajsambhusvt** [ros-controls/ros_control#504]
Hello, I have been trying to catkin_make the franka_ros package and the following error is obtained (also attached CMakeOutput.log)- 

CMake Error at /home/trec/catkin_ws/devel/share/controller_interface/cmake/controller_interfaceConfig.cmake:113 (message):
  Project 'controller_interface' specifies
  '/home/trec/catkin_ws/src/ros_control/controller_interface/include' as an
  include dir, which is not found.  It does neither exist as an absolute
  directory nor in
  '/home/trec/catkin_ws/src/ros_control/controller_interface//home/trec/catkin_ws/src/ros_control/controller_interface/include'.
  Check the issue tracker
  'https://github.com/ros-controls/ros_control/issues' and consider creating
  a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  franka_ros/franka_hw/CMakeLists.txt:7 (find_package)
[CMakeOutput.log](https://github.com/ros-controls/ros_control/files/9088104/CMakeOutput.log)

-- Configuring incomplete, errors occurred!
See also "/home/trec/catkin_ws/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:2102: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

I have installed the ros_control package using yay -S  ros-noetic-ros-control  and there were no errors during the installation. It would be great if you can advise on resolving this.

**Comment by bmagyar** [comment]
I don't know why you are building from source. If it was recommended by the maintainers of `franka_emika`, please get in touch with them. You don't have a problem with `ros_control`.
