### ISSUE TITLE
Why do JointStateHandle and JointHandle have empty constructors?

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#52]
Handles are pretty much useless when created with these constructors. They were added in 2a3c118, but the reason was not documented. What was the original purpose?, to do something like...

``` c++
JointStateHandle js; // Raw data not yet available
// Later on
js = JointStateHandle("name", &pos, &vel, &eff); // Raw data available
```

I don't like much the idea of constructing unusable objects.

**Comment by wmeeusse** [comment]
Our controllers often store a vector of handles as class members, which requires the handle to have an empty constructor. The alternative is to store vectors of (shared) pointers, but that's a bit more messy in its own way.

**Comment by adolfo-rt** [comment]
I understand your use case. What I then propose to do is to:
- Address #47, so make sure that when you _do_ initialize the raw data, no dangling pointers remain.
- Add (debug-only) assertions so that if you crash the process due to an invalid read, you get direct feedback of what went wrong, saving you the extra step of setting up a gdb session to find the source of the crash.

The above must be implemented for each handle type.

This would be a good compromise for me. @wmeeusse, are you OK with it?.

**Comment by wmeeusse** [comment]
Ya, that sounds like a good plan!

**Comment by adolfo-rt** [comment]
There is one scenario currently not covered by the validity tests:

``` c++
double cmd;
hardware_interface::JointStateHandle state_h;
hardware_interface::JointHandle cmd_h(state_h, &cmd); // would throw if cmd == 0
cmd_h.getPosition(); // crash
```

I see no clean and simple way to handle it. I'm closing the issue, but wanted to leave the scenario documented for the record.
