### ISSUE TITLE
controller_namager update does not seem to be realtime safe

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#6]
Hi Wim,

Rob Wilson and I just found that ros::Time::now() results in a syscall.

Do you all have a good way to test if the code is realtime safe? If you're willing to install RTAI on a machine then we can provide you with our installation instructions and the method that we are using to check for syscalls.

**Comment by wmeeusse** [comment]
That's a good catch. Ya, I'd love to get your instructions on how to check for syscalls.

**Comment by advaitjain** [comment]
Here's the method that Rob has come up with:
Run your code on a computer with RTAI installed in a realtime thread. Then do 'watch cat /proc/rtai/scheduler' to see if syscalls are happening. Narrowing down the source of the syscalls unfortunately is simply commenting out parts of the code, recompiling and running to check if the calls persist.

Currently our RTAI installation instructions are on an internal wiki but I can copy them over to some place else if you all might find it useful. We also have some simple example code for creating and running a hard realtime RTAI thread if that is of interest.

**Comment by wmeeusse** [comment]
Fixed
