### ISSUE TITLE
Should the controller_manager's services be namespaced?

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#64]
I noticed when using `rosrun controller_manager spawner` there isn't an argument to specify a namespace, and it expects the load_controller service to be at `/controller_manager/load_controller`. Is this on purpose or should I add this feature to the spawner?

Currently, my robot as its controller manager services at
`rrbot/ros_control/controller_manager/load_controller`

**Comment by wmeeusse** [comment]
I'm not sure I understand your comment exactly, but when you start the controller manager and spawner in the same namespace, they'll talk to each other.  So, in your example, you could spawn both of them in the rrbot/ros_control namespace, and they'll still happily talk to each other.  Does that behavior cover your usecase? If not, could you describe in a bit more detail what features you're talking about?

**Comment by davetcoleman** [comment]
I added the command line argument in https://github.com/willowgarage/ros_control/pull/56

**Comment by wmeeusse** [comment]
@davetcoleman Could you still comment on my question above?

**Comment by davetcoleman** [comment]
From my understanding, the only way to start the controller manager and spawner in the same namespace is to use `roslaunch` with a, for example, `ns='/robot/ros_control/'` attribute. If you want to use the spawner without `roslaunch`, using `rosrun`, you'd need a command line argument for the namespace, as I have added.

**Comment by wmeeusse** [comment]
Okay, that makes sense. For that functionality I've typically used the command line tools in ros_control, e.g. "rosrun controller_manager controller_manager spawn rosot/ros_control/controller_name". If those tools don't cover your needs, I'm happy to merge in the new feature in spawner. Let me know what you think.

**Comment by davetcoleman** [comment]
I wasn't aware of those command line tools but I still think this is a simple feature that shouldn't hurt anything.

**Comment by wmeeusse** [comment]
Merged in the change!
