### ISSUE TITLE
organization icon for ros-controls

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_control#68]
![ros_controls_dots](https://f.cloud.github.com/assets/1253450/707476/2b85cc3e-de1d-11e2-8ed8-946fa8bef099.png)

**Comment by wmeeusse** [comment]
Love it, nice work!

**Comment by jbohren** [comment]
(just updated to remove some space between connectors)

**Comment by davetcoleman** [comment]
Sweet!

**Comment by jbohren** [comment]
Who here actually has admin rights to set the org icon to this, anyway?

**Comment by ahendrix** [comment]
I do. I think it's set, and should be showing up shortly.

**Comment by ahendrix** [comment]
Done. Thanks for the awesome logo!

**Comment by jbohren** [comment]
Sweet, thanks!

**Comment by adolfo-rt** [comment]
+`std::numeric_limits<long double>::max();`

Yeah!

**Comment by jbohren** [comment]
@adolfo-rt that's a strange-looking emoji...

**Comment by yamokosk** [comment]
Very nice!

On 06/25/2013 11:57 PM, Jonathan Bohren wrote:

[https://f.cloud.github.com/assets/1253450/707473/edb68cd6-de1c-11e2-9812-a961aa7a6e18.png]https://f.cloud.github.com/assets/1253450/707473/edb68cd6-de1c-11e2-9812-a961aa7a6e18.png
