### ISSUE TITLE
Where should main development take place?

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#69]
Now that the hydro-devel branch is in place, does it make sense to keep master alive?.

**Comment by davetcoleman** [comment]
It would be much easier keeping track of changes to remove it.

**Comment by adolfo-rt** [comment]
Makes sense, I just pushed today some changes in master, while others are pushing to hydro-devel. A similar discussion is going on over ros_controllers and the consensus seems to be to get rid of master. Shall we then put them up to date with each other and remove master?.

**Comment by davetcoleman** [comment]
+1

**Comment by davetcoleman** [comment]
I've been committing to `hydro-devel`

**Comment by adolfo-rt** [comment]
API additions and non-API-breaking changes should go to hydro-devel, and master is reserved for API-breaking changes then?. I just don't know where the line is drawn here, as it's the first time I work with the ros-style branch model.

**Comment by wmeeusse** [comment]
@adolfo-rt  Yes, you're right on!  Let me just add that the hydro-dev branch only gets locked for API changes once it gets officially released into Hydro.  I'm not sure if we already passed the lockdown date or not, but until the lockdown you can still break the API in the hydro-dev branch.

**Comment by adolfo-rt** [comment]
Thanks for the clarification. Now I got it!. I don't have any API breaking changes under the sleeve, but wanted to know how to proceed in such a case.

**Comment by davetcoleman** [comment]
The Hydro freeze date was officially the Friday before last, so at this point we should be adding new features to a "indigo-devel" branch for ROS Indigo Igloo that will be released next year. **I'd propose we rename "master" to "indigo-devel" to clarify.**

We can still sneak some last minute stuff into Hydro as long as we aren't breaking the API.

Also, should we still have two branches each for groovy and fuerte, or could we clean those up to just one branch each?

**Comment by adolfo-rt** [comment]
I have API additions in master that I'd like to incorporate into Hydro. AFAIK this should be OK.

**Comment by davetcoleman** [comment]
+1 to merging into Hydro and releasing a new version into bloom, but i have 2 pending pull requests that I'd like to get in too
