### ISSUE TITLE
[proposal] trajectory_interface 

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_control#74]
It's looking like another module of the ros_control toolchain that we could provide a pluggin-able interface for is trajectory interpolation.

The goal here would be to provide a simple interface that includes:
- standard processing of [JointTrajectory](http://ros.org/doc/api/trajectory_msgs/html/msg/JointTrajectory.html) messages and [CartesianTrajectory](http://www.ros.org/wiki/trajectory_msgs/Reviews/Cartesian%20Trajectories_API_Review_2013_06_05?highlight=%28PackageReviewCategory%29) (still being prototyped) messages
- recomputing a trajectory if requested
- sampling a trajectory at an arbitrary time
- specification of different standard interpolation techniques (cubic, quintic, slerp)
- joint-space or cartesian space output (or both)

There should be an emphasis on dealing not just with long discrete trajectories, but also for use as an interpolator for streaming contexts like teleoperation. To that end, depending on performance, it might make sense to also provide an interface for `JointTrajectoryPoint` and `CartesianTrajectoryPoint`.

This is based on discussion on joint trajectory controllers and the idea to split some of the features of the current PR2 joint trajectory controllerthe robot control SIG here:  
https://groups.google.com/forum/#!topic/ros-sig-robot-control/VseNnkqXBkY

---

@wim @adolfo-rt @bit-pirate @davetcoleman

**Comment by wmeeusse** [comment]
Sounds like a good plan!  Not sure where you say 'pluggin-able' interface, if you mean a plugin that can be loaded at runtime, or just a set of re-usable components in a library that can be integrated at compile time by a controller builder.  For this use case I'm imagining that the latter makes most sense.

**Comment by jbohren** [comment]
I did mean a library that can be loaded at runtime. We can still build a library of loadable tractory generators / interpolators, but I like being able to load such components as plugins.

**Comment by sachinchitta** [comment]
Might be worthwhile looking at all the options we have before diving deeper and re-inventing the wheel. For the interpolation itself, the options include (1) KDL (2) Reflexxes (3) MoveIt! itself does interpolation inside robot_state and also (for trajectory generation) has the iterative spline smoother (4) Some of the old code in arm_navigation could be reused (5) I think Bullet has some interpolation code that might also be available through TF. I would prefer not coming up with a whole new solution but wrapping the existing ones through a really lightweight interface.

**Comment by jbohren** [comment]
@sachinchitta 

>  I would prefer not coming up with a whole new solution but wrapping the existing ones through a really lightweight interface.

Which is exactly why I'm describing this as a trajectory interface, and not a trajectory library, and suggesting that it be a plugin-able interface which we can use to give all of these different implementations a common API.

**Comment by jbohren** [comment]
(of course those lightweight plugins need to reside somewhere)

**Comment by wmeeusse** [comment]
Having a lightweight interface is a requirement that is independent of loading code a runtime vs loading code at compile time.  However, loading code at runtime requires a bit more tooling, and makes it harder to reuse the code in a different setup.  A library is still the easiest way to share and reuse code across different systems.  Also, when you can resolve problems at compile time, that is generally preferred to solving problems at runtime.  So, I guess for this project I'm still missing the usecase that justifies/requires the use of loading code at runtime. Could you elaborate a bit more on who the users will be of these tools, and how they will use them?

**Comment by jbohren** [comment]
@wmeeusse 

> So, I guess for this project I'm still missing the usecase that justifies/requires the use of loading code at runtime. Could you elaborate a bit more on who the users will be of these tools, and how they will use them?

Well if the library is being used by a controller, and the controllers are dynamically-loaded, then either the controllers need to depend on this library of trajectory wrapper implementations or they need to be dynamically-loadable. It simply decouples the dependencies.

**Comment by wmeeusse** [comment]
It seems okay if a controller that needs trajectories depends on a library of trajectory implementations. In the end, you can't get away from that dependency; it'll either be a compile time dependency or a run time dependency.  So I'm still not sure what we're gaining by moving to runtime plugins. Sorry to keep pushing on this one, I'd love to get a better understanding of the motivation behind the design.

**Comment by bit-pirate** [comment]
Currently, I can't see any need on my side for loading/switching various interpolation methods on runtime. I still like the idea though.

Having dynamically loadable interpolation and control methods would allow to create new flavours of controllers by just writing a launcher. Otherwise we will need to implement each combination as a separate controller (e.g. interpolation_A_control_method_B_controller, interpolation_B_control_method_B_controller, interpolation_A_control_method_A_controller etc.).

**Comment by jbohren** [comment]
> It seems okay if a controller that needs trajectories depends on a library of trajectory implementations. In the end, you can't get away from that dependency;

Except with a plugin-based interface the controllers themselves only need to depend on the interface, and not the interpolation implementations. That way one person can write a controller, and an unconnected person can write an interpolator, and then a third person can use both without having to create a new controller. It also allows simple and lightweight controller configuration as @bit-pirate described above.

**Comment by adolfo-rt** [comment]
I think there is a big need for a trajectory interface, and I see the gain in giving it plugin support, for the same combinatorial explosion reason given by @bit-pirate ìn an [earlier post](https://github.com/ros-controls/ros_control/issues/74#issuecomment-20388164). The extra tooling effort will be worth it. Further, if a usecase prefers to have a build-time dependency, you can always choose to not use runtime loading and link to a particular library.

**Comment by davetcoleman** [comment]
> Otherwise we will need to implement each combination as a separate controller (e.g. interpolation_A_control_method_B_controller, interpolation_B_control_method_B_controller, interpolation_A_control_method_A_controller etc.).

I'm not quite convinced we need run time plugins for this either - that adds a small additional amount of complexity to an already complex controller framework. Instead, could we not have each controller have a build dependency on all the available interpolation methods, and then choose which one a controller uses based on a run time parameter/argument? I'm assuming we won't have _that_ many interpolation methods - @sachinchitta named 5 possible ones but will we really have the time to implement lots of different ones?

**Comment by sachinchitta** [comment]
I prefer runtime plugins - makes it easier to test out different combinations easily. If we had a particular solution for trajectory interpolation and decided to just use that (which might not be a bad idea either), we could have just gone with it. Failing that, I would certainly prefer runtime plugins. Hopefully, we can converge on one library for this but the plugin will keep things flexible in the meantime.

**Comment by kphawkins** [comment]
I'm looking forward to using this, but I'd like to request that we settle on an interpolation interface which works for most basic use-cases.  I propose that at the controller runtime level, the interface consumes position and velocity vectors of the current state and returns position, velocity, and acceleration vectors of the target state.

As for the plugin/library discussion, I feel like it would be best to just to just settle on the Reflexxes library until someone makes a strong case for using something else.  @jbohren's [code](https://github.com/jhu-lcsr/reflexxes_controllers/blob/master/reflexxes_effort_controllers/src/joint_trajectory_controller.cpp) looks pretty nice when compared to the old [PR2 solution](http://ros.org/doc/groovy/api/robot_mechanism_controllers/html/joint__trajectory__action__controller_8cpp_source.html), no offence.

In keeping it more simple for the controller writers, I feel it would be easier to just link it in.  Else, you have to be fairly clear that you now have to worry about 2 layers of plugins, the interpolating layer, and the controller layer.  Once we actually have people using different interpolators for controllers it would be easy to update everything to plugins.

**Comment by adolfo-rt** [comment]
All,

I'm posting here an extended variant of a comment made on the robot control sig. I'm currently working on an implementation of the `JointTrajectoryActionController` that should be robot-agnostic, and trajectory-representation-agnostic. It's not finished yet, but it would be nice to have some feedback on how the trajectory interface is looking.

### Trajectory segment

In order to support a new trajectory representation, you only need to provide an implementation of a **trajectory segment** class, that conforms to an expected inteface (expected as in generic programming interface, not OO programming interface). An example follows:

``` c++
class MySegment
{
public:
  // It should define a Scalar type
  typedef double Scalar;

  // It should define Time and State types. They can be anything
  typedef Scalar Time;

  struct State
  {
    std::vector<Scalar> position;
    std::vector<Scalar> velocity;
    std::vector<Scalar> acceleration;
  };

  // It should be default-constructible
  MySegment();

  // It should provide a constructor from Time-State boundary conditions
  MySegment(const Time& start_time, const State& start_state,
            const Time& end_time,   const State& end_state);

  // It should allow sampling a state for any time input (realtime-safe method)
  void sample(const Time& time, State& state) const;

  // It should allow querying its size (dimension)
  unsigned int size() const;

  // It should allow querying start/end times
  Time startTime() const;
  Time endTime()   const;
};
```

Notice that `Time` and `State` can be anything, ie. `Time` could be `ros::Time`, and `State` could be `double`, if it makes sense to your application.

**Note:** For some segment representations (Reflexxes-based?), the start state might be of little significance, but I think it does no harm to have it there, as other representations such as splines do need it.

### Trajectory

A trajectory is no more than a container (preferably a sequence container) with segments sorted according to their start time, like so:

``` c++
typedef std::vector<MySegment> MyTrajectory;
```

At this point, there are some useful bits of functionality that you can leverage without writing additional code:

``` c++
MyTrajectory traj; // Populate...
typename MyTrajectory::Time time = ros::Time::now().toSec();

// Find segment active at a given instant: Container input
typename Trajectory::const_iterator it = findSegment(traj, time); // 'it' points to active segment

// Find segment active at a given instant: Range input
typename Trajectory::const_iterator it = findSegment(traj.begin(), traj.end(), time); // 'it' points to active segment

// Sample trajectory at a given time
typename MyTrajectory::State state;
typename Trajectory::const_iterator it = sample(traj, time, state); // 'it' points to active segment
```

### Usecase: JointTrajectoryController

For the specific case of joint trajectories, where the state is a multi-dof `<pos, vel, acc>`  triplet, there are additional methods that allow you to populate a trajectory from a `trajectory_msgs::JointTrajectory` message. This is work-in-progress, but if your segment's `Time` and `State` implementation match that of `MyTrajectory`, you should be able to do the following:

``` c++
MyTrajectory prev_traj; // Populate...
std::vector<std::string> joint_names; // Names follow ordering of prev_traj
std::vector<bool> is_continuous_joint; // Entries == true are continuous joints

trajectory_msgs::JointTrajectory msg; // We got this from a callback

// We now want to combine prev_traj with the contents of msg, and face these problems:
// - Joints in msg might not be ordered like prev_traj
// - Handle gracefully multi-loop commands on continuous joints
// - We want to preserve only the useful parts pf prev_traj and msg, and discard the rest

typename MyTrajectory::Time time = ros::Time::now().toSec();
MyTrajectory combined_traj = combine(prev_traj,
                                     msg,
                                     time,
                                     joint_names,         // Enforces joint ordering (optional)
                                     is_continuous_joint) // Deals with continuous joints (optional)
```

What I have described so far is the heart of the `JointTrajectoryController`. If we want to have a plugin-based trajectory representation, it should suffice to make the plugin base class conform to the interface of the `MyTrajectory` example above.

**Comment by davetcoleman** [comment]
Adolfo has released his `JointTrajectoryController` and I think this fulfills much of this issue. I'm cleaning up old issues so closing this for now. Feel free to reopen if desired.

**Comment by adolfo-rt** [comment]
I just want to note that the `JointTrajectoryController` is a joint-space interpolator. We could repoen this issue in a later time if and when there is interest and available manpower for Cartesian (or other types) of interpolators.

The generic trajectory interface discussed earlier in this thread is implemented and used by the `JointTrajectoryController`. It could be used for Cartesian interpolation as well. All that needs to be done is define the appropriate State and Segment types. The interface currently lives [here](https://github.com/ros-controls/ros_controllers/tree/hydro-devel/joint_trajectory_controller/include/trajectory_interface).
