### ISSUE TITLE
ros_control for Hydro still at 0.4.0-2, farm builds broken

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#89]
The version of ros_controllers got recently bumped to [0.5.0-0](https://github.com/ros/rosdistro/blob/master/hydro/release.yaml#L1297) in the rosdistro release file for Hydro, while ros_control is still on [0.4.0-2](https://github.com/ros/rosdistro/blob/master/hydro/release.yaml#L1282). This is causing the ros_controllers build to fail, as it's expecting headers from ros_control 0.5.0-0 to be available. Could you please issue a rosdistro PR to bump ros_control to 0.5.0-0 as well?.

**Comment by davetcoleman** [comment]
I'm not sure why this wasn't automatically PR'ed by the new bloom scripts (it usually does this now) but I need to add myself to the maintainer tag so that I get these warning emails.

Fixed in https://github.com/ros/rosdistro/pull/1452

**Comment by davetcoleman** [comment]
New pull request https://github.com/ros/rosdistro/pull/1454

**Comment by adolfo-rt** [comment]
Thanks!
