### ISSUE TITLE
templated controller implementations to reuse code for multiple hardware interfaces?

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#9]
I can imagine that it would be nice if the Cartesian and position effort controllers could work with an EffortJointInterface and an EffortMotorInterface.

Would it be possible to have a templated class for the controllers that can be reused with both the EffortJointInterface and an (as yet undefined) EffortMotorInterface?

If this is a possibility then we could go ahead and define a MotorCommandInterface and EffortMotorInterface. Maybe there is an opportunity for using templates for this too?

Adding @sachinchitta and @vpradeep07 to this conversation.

**Comment by vpradeep07** [comment]
Without knowing exactly what the `EffortMotorInterface` looks like, it might be a bit too soon to force it to match all the  calls to the `EffortJointInterface`, so that we can template things against both.

Maybe there's room to make the Cartesian controllers a thin wrapper around a math/control library that could easily be used with both a `JointCommandHandle` and a `MotorCommandHandle`.  That would be one way to leave some flexibility and not smush both interfaces to be the same.

**A small aside:**
If your motors look an awfully lot like joints, could you just add all of them to the `JointEffortInterface`?  If motors always look like joints, then maybe we shouldn't be templating controllers against both interfaces, and instead flatten both Motors and Joints into a single interface type (and remove the word "joint" from the interfaces)

**Comment by advaitjain** [comment]
The EffortMotorInterface would be identical to the EffortJointInterface except that getPosition and getVelocity would return the estimate of the joint angle and velocity using the motor encoders. And getEffort would return the torque applied by the motor.

For the EffortJointInterface the joint encoders would be used and a torque sensor at the joint.

Ideally, a robot like the PR2 would have an EffortMotorInterface and not an EffortJointInterface. It could have an EffortJointInterface if there were some model for the belt stretch, friction etc.

---

A think wrapper around the control library sounds good. But there is the question of making function calls to get the joint angles, Jacobian etc.

---

I don't think we should add the motors to the JoinEffortInterface because the controllers that use only motors or joints should not require the robot to have an interface with both.

Motors will often look a lot like joints, but there could be funky combinations. e.g. use the motor encoders for computing velocity, but joint encoders for position. Or using motor encoders for some joints and joint encoders for others,

---

More generally, I think my question is this: (I'm using 'have' with interfaces to match the notion of composition)

Is there a way to let someone writing a robot class to have the flexibility to use a combination of sensors and have multiple interfaces that can be used by the same open source controller in ros_control.

One key idea is this:
As a robot class writer, I would like to be able to have multiple (multiple in terms of semantics, e.g. motor or joint encoders, not necessarily the interface class) interfaces that could each be used with the same open source controller. And as person working on robot control, I would like to be able to choose which interface to use via the controller.yaml file.

e.g. if my robot has only joint or motor encoders, then I have an interface with those. If my robot has both joint and motor, then I can create multiple interfaces for the controller by mixing and matching, as it suits me. (a similar type of mixing and matching would happen with robots that have both current sensing and some form of torque sensing (at the motor, joint or both)).

I feel that some of this could be achieved by changing the names (like Vijay suggested). Could having multiple interfaces for the same controller be a problem for the controller_manager?

**Comment by advaitjain** [comment]
Based on discussion with Wim and Vijay (for documentation and for the benefit of Sachin and Rob):
1. Adding motors to the `EffortJointInterface` would work as a way to use motors with the existing controllers (the `EffortJointInterface` would expose 14 different names, 7 for the joints and 7 for the motors). We could not think of a better name so we will stick with calling it `EffortJointInterface`.
   But maybe renaming the functions would still be worthwhile?
2. Wim had started adding support for multiple rates in the controller manager, but things were getting messy. So going to push that burden to the individual controllers.
3. Wim and VIjay have started on a resource manager that would help detect cases of two controllers trying to command the same actuator. Essentially a function in the robotHW class.

I'm closing this issue. But we should come back and revisit the names sometime later, I think.
