### ISSUE TITLE
Typos in package.xml & manifest.xml in hardware_interface

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-controls/ros_control#90]
Identical to #78, but for `hardware_interface`. Just caught my eye.

**Comment by davetcoleman** [comment]
What are the typos?

**Comment by gavanderhoorn** [comment]
> "Interaface" -> "Interface" in both package.xml and manifest.xml of the transmission_interface package (description element).

but then for the `hardware_interface` package.

**Comment by davetcoleman** [comment]
Fixed in https://github.com/ros-controls/ros_control/commit/5635d7fd1d0a736b3b6999f630fc74963e4db2c8

Feel free to just send a pull request with fixes like this, they are easily merge-able and much appreciated!
