### ISSUE TITLE
How to know type of hardware_interface is being used

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#99]
If you have a hardware interface that implements more than one type - i.e. EffortJointInterface, PositionJointInterface, VelocityJointInterface - how can you tell which one is currently being used/written to? For example, in the Gazebo ros_control plugin I want to be able to implement all three of the above interfaces, and send commands to a simulated robot depending on which method is being used. I do not see a method to get this property - the closest thing I have found is for controllers, which have a `getHardwareInterfaceType` method - but this isn't accessible from the hardware_interface itself.

Thanks!
@adolfo-rt @jbohren

**Comment by adolfo-rt** [comment]
Currently there are no `HardwareInterface`s implementing more than one command type.

From your usecase description, I think what you want is to register the same joint to _multiple_ `HardwareInterface`s in your robot hardware abstraction. Then, a controller that wants to use that joint in position mode will get a handle from the `PositionJointInterface`, while a controller that wants to use it in effort mode will get a handle from the `EffortJointInterface`. Resource management will make sure that the two controllers don't come in conflict with one another (eg. not let them run concurrently).

If a controller implements the `controller_interface::Controller` interface, there's only one available `HardwareInterface` anyway, so you can't choose from which interface you get your joint handles.

**Comment by davetcoleman** [comment]
I think I have figured out my question...

But to explain, we have this default [robot_hw_sim](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp#L197) that implements `robot_hw` for Gazebo. In it, joints can be any of the three hardware interface types. What I want is to be able to send "commands" to Gazebo based on the type of interface - force, position or velocity. Currently it only can send force (effort) commands to Gazebo, so this is a todo. But I think I see how to do this properly now.

**Comment by adolfo-rt** [comment]
To complement my previous post, when you have a single joint expose multiple control modes, you need to do some bookkeeping to keep track of which control modes are active for each joint, and expose methods for mode switching. Active control modes will affect, for example, how transmissions propagate, eg. which commands should be propagated from joint to actuator space?.

The recommended way for switching hardware control modes is discussed in [this](https://github.com/ros-controls/ros_control/wiki/control_mode) wiki entry.

**Comment by davetcoleman** [comment]
The above pull requests answer this issue, closing.
